const express = require('express');
const router = express.Router();
const clientController = require('../controllers/ClientController');
router.get('/', clientController.getAll);
router.get('/:id', clientController.getById);
router.post('/', clientController.create);
router.put('/', clientController.update);
router.put('/enable/:id', clientController.enable);
router.put('/disable/:id', clientController.disable);
router.put('/changePassword', clientController.changePassword);
router.post('/recoverPassword', clientController.recoverPassword);
module.exports = router; 